
services:
  app:
    build: ./
    command: ./wait-for-postgres.sh db ./app
    env_file:
      - .env
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    depends_on:
      - db
    environment:
      - DB_PASSWORD=${DB_PASSWORD}

  db:
    restart: always
    image: postgres:latest
    env_file:
      - .env
    volumes:
    - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5436:5432